#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
discord &

bspc monitor -d 󰍹 󰨞  󰙯

bspc config border_width         2
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^4'
bspc rule -a Firefox desktop='^4'
bspc rule -a firefox desktop='^4'
bspc rule -a Zathura desktop='^1'
bspc rule -a discord desktop='^5'
bspc rule -a code desktop='^3'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true
bspc config pointer_modifier 	super

bspc config normal_border_color "#1a1b26"
bspc config focused_border_color "#f7768e"

feh --bg-scale /home/firocore/Wallpapers/City36.jpg &
picom -b &
bash ~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr
#~/.config/bspwm/bin/bspborder &
#pkill borders ; borders &
